<!DOCTYPE html>
<html>
<head>
    <title>Basic PHP Example</title>
</head>
<body>

    <h1>Welcome to My Website</h1>

    <?php
    // This is a single-line comment
    echo "Hello, World! This text is generated by PHP.";
    ?>

</body>
</html>
